dbt_worker:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('OUTPUT_PROJECT') }}"
      dataset: "{{ env_var('OUTPUT_DATASET') }}"
      threads: 4
      timeout_seconds: 300
      location: "{{ env_var('OUTPUT_LOCATION') }}"
      priority: interactive
